version: '3.9'

services:
  db:
    image: postgres:15
    container_name: test_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  api:
    build: ./api
    container_name: test_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./api:/app

  frontend:
    build: ./frontend
    container_name: test_frontend
    restart: always
    depends_on:
      - api
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app

volumes:
  postgres_data:
